// To future editors, here is a convenient link to the AsciiDoc syntax
// quick reference
//   https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

= D16N Specification 1.0
bettermarks GmbH
v1.0, 2024-10-23
:toc: right


// TODO: Include links back to this repo, for the case that reader is viewing
// github pages.

[abstract]
.Abstract
The d16n (depseudonymisation) specification describes a protocol for third-party apps to display user identifying information without having it pass through their servers.
This is written in the context of offering learning tools to children and their teachers, without needing to process personal data.


== Introduction

// TODO: Repeat parts of the abstract and expand on it

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in https://www.rfc-editor.org/rfc/rfc2119[RFC 2119].

=== Terminology

CORS:: Cross-Origin Resource Sharing
Clear Name:: A name that identifies an End-User to another user of the IDP. e.g. the name of a student used offline in the classroom by their teacher.
End-User:: A human.
Identity Provider (IDP):: Identity Provider
Pairwise Pseudonymous Identifier (PPID):: A Pseudonym, as we define it here, that is unique to each RP-IDP pair.
Pseudonym:: An user identifier issued from the IDP to the RP. But one that is not Personally Identifying Informatation (PII).
RP Client:: An application running on the End-User's device, issued by the Relying Party. For example, this may be a mobile app or a JavaScript app running in the End-User's web browser.
RP Server:: A server or collection of servers under the control of the Relying Party
Relying Party (RP):: Client application that relies on the IDP for user authentication.

== Overview

// I'm not very happy with this image yet. It would be nice to get grouping boxes
// around pieces like they have in these diagrams.
//   https://diagrams.mingrammer.com/docs/getting-started/examples#message-collecting-system-on-gcp
//
// I'm also wondering if it would make sense to split into two images
// the first that indicates how we establish the path of access i.e. acquire
// the access token and a second that shows the containment of the data.
// I have a sketch in my notebook.

image::images/01-overview.svg["Overview of RP and IDP interactions",60%,opts=interactive,align=center]

The general flow is the following

. The current user authenticates with the IDP. _Non-normative_
. The current user performs authorization and the RP Server stores a *d16n Access Token*.
. The RP Client obtains one or more Pseudonyms of other users the current user wishes to see the Clear Names of. _Non-normative_
. The RP Client obtains the *d16n Access Token* from the RP Server.
. The RP Client requests the Clear Names from the IDP using the *d16n Resolve API*.
. The RP Client displays the Clear Names to the current user.

In this way, Clear Names stored by the IDP are transmitted.

== Authorization

[#_the_d16n_access_token]
=== The d16n Access Token

The RP obtains a d16n access token on behalf of the user via an OAuth 2.0 <<RFC6749>> authorization grant.
The Authorization Code Grant flow MUST be used.
Extensions to the Authorization Code grant such as PKCE <<RFC7636>> are acceptable.

// Needs to be auth code grant because ... it's the safest. No need to enter
// password on foreign site.

The access token should be requested with a `d16n` scope.

The `d16n` scope permits access the the Resolve API.

// Want to say that implementers may want to give this to teachers but not
// to students.


It is recommended that access token lifetime, `exp - iat`, be kept short,
on the order of 60 seconds as the access token will be sent to the RP Client
where it is not possible to ensure secret keeping.
See 4.1. of <<RFC7519>> for further details about `exp` and `iat` claims.


// Suggest the IDP elide the user confirmation prompt?

// This isn't really helpful...
It is possible to perform OAuth 2.0 with PKCE in the RP Client to obtain the access token, but we recommend against it.
It's not conformant to issue refresh tokens to a client-side only implementation.
Moreover, IDPs implementing this specification are not required to support it.

// TODO: should we include an example of one or more of the requests/responses
// or include something like a sequence diagram here... ?

=== Refresh Token

We recommend the IDP issue a Refresh Token along with the d16n Access Token.
This usually improves user experience as the alternative requires reperforming OAuth 2.0 authorization, sending the user along a series of redirects, which interrupts their use of the application.

== Pseudonyms

This specification assumes that there exists an access controlled API to retrieve the Pseudonyms of other users.

For example, in a learning app context, a teacher would have access to API that returns the Pseudonyms of the members of one of their classes.

== The Resolve API

// It would be better to be able to include an openapi spec document.
// There is an https://openapi-generator.tech/docs/generators/asciidoc
// but unfortunately it seems to ignore our examples and the links are
// broken.
//
// TODO: try https://github.com/luftfartsverket/openapi-to-asciidoc

The Resolve API is called from the RP Client to resolve Pseudonyms into Clear Names.

// TODO: replace this with a pretty SVG.
----
    +-----------+                                             +-------+
    |           |                                             |       |
    |           | --------------(1) preflight --------------> |       |
    | RP Client | <------------(2) preflight ok-------------- |  IDP  |
    |           |                                             |       |
    |           | ----------(3) request clear names---------> |       |
    |           | <----------(4) return clear names---------- |       |
    |           |                                             |       |
    +-----------+                                             +-------+
----

=== Endpoints

These endpoints are implemented by the IDP.

`/users/{id}`::
    Resolves the Pseudonym of a single user.
    The `id` is the Pseudonym to resolve.

`/users/`::
    Batch resolve. Resolves multiple Pseudonyms in a single request.
    Takes a single query parameter `ids`, a comma separated list of Pseudonyms
    to resolve.

// I wonder if it would be possible to have these discovered somehow...

=== Preflight

Each endpoint must support the `OPTIONS` method.

Preflight requests are issued automatically by the Web-Browser for any web based client.
The RP does not need to take any further steps.

An example request is included for the benefit of an implementing IDP to give an impression of what they can expect to receive.

.Informative preflight request example
----
OPTIONS /path/to/d16n/users/550e8400-e29b-41d4-a716-446655440000 HTTP/1.1
Host: idp.example.com
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
Origin: https://rp.example.com
----


[#_the_preflight_response]
==== The Preflight Response

The IDP must respond to the `OPTIONS` request for the d16n endpoints.
It should respond with a Status Code of `200`.

The following headers are necessary. This is however non-normative.
Implementers are required to keep pace with standards and verify browser support themselves.

// TODO(dan): add missing Access-Control-Allow-Credentials to internal spec

|===
| Header | Value

| `Access-Control-Allow-Origin`
a| The Origin of the RP Client. This may be the Host of the RP Server. e.g. `https://rp.example.com`. If the request is received from an unpermitted Origin, the IDP should not return this header.

NOTE: `*` is not permitted as d16n resolve requests include credentials.

TIP: The IDP can validate the `Origin` header of the request and return the value as this header value verbatim.

| `Access-Control-Allow-Methods`:
| `GET`

| `Access-Control-Allow-Headers`:
| `authorization`

| `Acces-Control-Allow-Credentials`
| `true`

| `Vary`
| `Origin`

|===

See <<FETCH>> for further details.

// TODO: include OPTIONS response example?

.Informative preflight response example
----
HTTP/1.1 200
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: https://rp.example.com
Vary: Origin
----

=== Resolve Request

The RP Client makes this request to the IDP.
The xref:_the_d16n_access_token[d16n access token] MUST be as a Bearer Token per <<RFC6750>>.

The Pseudonym to resolve it supplied as the final path component of the URL

Non-normative example

----
GET /path/to/d16n/users/550e8400-e29b-41d4-a716-446655440000 HTTP/1.1 <1>
Host: idp.example.com <2>
Authorization: Bearer imAkPG4UVhRf-TM9NcghCA <3>
Origin: https://rp.example.com
----
<1> Endpoints may be rooted at an arbitrary base URL
<2> The IDP's d16n server
<3> The d16n access token is supplied as a bearer token

=== Resolve Response

All resolve responses should have CORS headers, the _Access-Control-Allow-*_ headers,
with the same values as in xref:_the_preflight_response[the Preflight Response].

All responses should have a `Content-Type` of `application/json`.

==== Success

|===
| Status Code | Description

| 200
| An object containing Clear Names

|===

The response body is a JSON object with three fields

`id`:: The Pseudonym
`firstname`:: A first name (a.k.a given name) belonging to the person identified by the Pseudonym.
`lastname`:: A last name (a.k.a family name or surname) belonging to the person identified by the Pseudonym.


.Informative example success response
----
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: https://rp.example.com
Vary: Origin
Content-Type: application/json

{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "firstname": "Betty",
  "lastname": "Free"
}
----

==== Errors

|===
| Status Code | Description

| 401
| Unauthorised. Token expired, invalid or not provided

| 403
| The token is valid but the user is not permitted to make the request. This can be used also when the token does not have the `d16n` scope. This status code should not be used when access is not permitted for a particular `id`, instead 404 should be returned.

| 404
| The provided Pseudonym, `id`, is not known or does not correspond to a clear name the current user is allowed to access.

| 5xx
| Server Error. The RP should be prepared to handle unexpected errors.

|===

All error responses have the same response body structure.
A single JSON object with a single field

`detail`:: A useful message explaining the cause of the error. There is no expectation of whether this will be shown to the End-User. At a minimum it should help debug faulty implementations.

.Informative example error response
----
HTTP/1.1 401 Unauthorized
Content-Type: application/json <1>

{
  "detail": "Token expired"
}
----
<1> CORS headers omitted for brevity.

=== Batch Resolve Request

_TODO_

=== Batch Resolve Response

// I feel like we didn't consider what happens if a teacher is allowed
// to resolve only some students... it should be a 404.

==== Success

A successful response contains two fields

`data`:: A list of resolved user objects with the same structure as the successful Resolve Response object.
`errors`:: An object where each unresolved Pseudonym is a key and an error detail string is the value.

==== Errors

Status Codes for Batch Resolve are the same as for resolving a single Pseudonym except that `404` is not used and instead errors for individual Pseudonyms are reported in the Success response.

|===
| Status Code | Description

| 401
| Unauthorised. Token expired, invalid or not provided

| 403
| The token is valid but the user is not permitted to make the request. This can be used also when the token does not have the `d16n` scope. This status code should not be used when access is not permitted for a particular `id`, instead the error should be reported in the `errors` field of the Success response.

| 5xx
| Server Error. The RP should be prepared to handle unexpected errors.

|===


=== Access

When group membership is held by the IDP, it can be recommended to restrict the resolution of Pseudonyms to those belonging to members of a common group.

In a learning app context this might be stated as

. Teachers should be able to resolve the names of students in one of their classes
. Teachers should be able to resolve the names of other staff members at their school or learning institute.

== Implementation

All notes in this section are considered recommendations.
They are not mandatory for a correct implementation but are all worth consideration.

=== Authentication with OpenID Connect

A primary authentication method for the RP's app may be OpenID Connect with the IDP.
When this is the case, it's worth noting here that d16n provides an alternative for accessing some personal data often exchanged during OpenID Connect.

It is expected that the Standard Claims `given_name` and `family_name` from https://openid.net/specs/openid-connect-core-1_0-errata2.html#StandardClaims[ยง5.1] of <<OIDC>>,
and indeed many other Standard Claims, are not made available to the RP via the ID-Token or UserInfo endpoint so that they are not processed by the RP Server.


=== Privacy

The IDP SHOULD issue PPIDs, that is, for any user a different Pseudonym is issued for each unique RP.
In <<OIDC>> this is the `pairwise` subject identifier type.

// Not sure I should
Not doing this may allow activity to be correlated across multiple apps and a profile to collated, which encroaches on the user's privacy.

// Useful reading
// - https://openid.net/specs/openid-connect-core-1_0.html#Privacy ยง 17

// Maybe we need to have a section on risk?
// consideration of the use of the clear names inside the frontend app?

=== Treatment of PII in the Application

It should be made clear that the response of the d16n Resolve API contains personal data.
The RP should take care that this personal data does not leave the End-User device.

Client applications are often instrumented with telemetry in order to monitor their effectiveness and correct functioning.
It is important to prevent that PII is sent to any telemetry service

Clear Names should not be stored long-term on the End-User device.
It may make sense to cache the Clear Names in the client for a short amount of time to avoid overburdening the IDP.
We recommend that any caching of the Clear Names is expired when the End-User leaves the application.


=== On-Site IDPs

In the case of Schools running their identity server on their premises, schools may choose to further restrict access to the d16n Resolve API to the local network via firewall rules.

// Diagram to show this?

== References

[bibliography]
=== Normative References

* [[[FETCH]]] Anne van Kesteren. https://fetch.spec.whatwg.org/[Fetch]. Living Standard.
* [[[RFC6749]]] Hardt, D., Ed., "https://www.rfc-editor.org/info/rfc6749[The OAuth 2.0 Authorization Framework]", RFC 6749, DOI 10.17487/RFC6749, October 2012.
* [[[RFC6750]]] Jones, M. and D. Hardt, "https://www.rfc-editor.org/info/rfc6750[The OAuth 2.0 Authorization Framework: Bearer Token Usage]", RFC 6750, DOI 10.17487/RFC6750, October 2012.

[bibliography]
=== Informative References
* [[[RFC7636]]] Sakimura, N., Ed., Bradley, J., and N. Agarwal, "https://www.rfc-editor.org/info/rfc7636[Proof Key for Code Exchange by OAuth Public Clients]", RFC 7636, DOI 10.17487/RFC7636, September 2015.
* [[[OIDC]]] Sakimura, N., Bradley, J., Jones, M., de Medeiros, B., and C. Mortimore, "https://openid.net/specs/openid-connect-core-1_0-errata2.html[OpenID Connect Core 1.0 incorporating errata set 2]", December 2023.

// Maybe we want to reference the GDPR
//  https://eur-lex.europa.eu/eli/reg/2016/679/oj
