@startuml
skinparam backgroundColor white

rectangle IDP #FAC711

rectangle RelyingParty as "Relying Party" #D9D9D9 {
  rectangle Client #FAC711
  rectangle Server #85BCF0
}

IDP "Authorization" <-[#85BCF0]down-> Server
IDP "Clear Names" -[#FAC711]left-> Client
Client <-[#85BCF0]right- Server : Access Token

 legend
 |<back:#85BCF0>   </back>| Depseudonymized Area |
 |<back:#FAC711>   </back>| Pseudonymized Area |
 endlegend

@enduml
